MODEL_INFO = {
    "flask": {
        "name": "ANS Flask",
        "description": "Razonamiento profundo con respuestas educativas detalladas paso a paso.",
        "features": ["Explicaciones detalladas", "Pasos educativos", "Analogias y contexto", "Preguntas de seguimiento"],
    },
    "gapi": {
        "name": "ANS Gapi",
        "description": "Respuestas tecnicas directas con ejemplos de codigo y al grano.",
        "features": ["Solo codigo y tecnicismos", "Sin rodeos", "Ejemplos practicos", "Respuestas cortas"],
    },
    "modify": {
        "name": "Modify Code",
        "description": "Modo aprendizaje: absorbe conocimiento de cada conversacion y evoluciona.",
        "features": ["Aprende de cada mensaje", "Memoria colectiva", "Evoluciona con uso", "Recuerda todo"],
    },
}

KNOWLEDGE_BASE = {
    "html": "HTML (HyperText Markup Language) es el esqueleto de una pagina web. Define la estructura del contenido usando etiquetas como <div>, <p>, <h1>, etc.",
    "css": "CSS (Cascading Style Sheets) controla la presentacion visual: colores, espacios, tipografia, layout, animaciones y diseño responsivo.",
    "javascript": "JavaScript es un lenguaje de programacion que agrega interactividad, logica y dinamismo al navegador. Permite manipular el DOM, hacer peticiones HTTP y mucho mas.",
    "python": "Python es un lenguaje de programacion de alto nivel, interpretado y multiparadigma. Es popular por su sintaxis clara y se usa en IA, web, datos y ciencia.",
    "java": "Java es un lenguaje orientado a objetos, compilado y multiplataforma. Usa el JDK para compilar y es muy usado en empresariales y Android.",
    "flask": "Flask es un microframework de Python para crear aplicaciones web y APIs. Es ligero, flexible y ideal para prototipos y proyectos medianos.",
    "django": "Django es un framework web completo para Python. Incluye ORM, admin, autenticacion y seguridad integrada.",
    "react": "React es una libreria de JavaScript para construir interfaces de usuario componentizadas. Desarrollada por Meta (Facebook).",
    "nodejs": "Node.js es un entorno de ejecucion de JavaScript fuera del navegador. Permite crear servidores y APIs en JS.",
    "git": "Git es un sistema de control de versiones distribuido. Permite rastrear cambios en el codigo y colaborar en equipo.",
    "github": "GitHub es una plataforma de hosting de repositorios Git con herramientas de colaboracion, issues, pull requests y CI/CD.",
    "sql": "SQL (Structured Query Language) es el lenguaje para gestionar y consultar bases de datos relacionales como MySQL, PostgreSQL y SQLite.",
    "mysql": "MySQL es un sistema de gestion de bases de datos relacional, uno de los mas populares del mundo. Es open source y muy rapido.",
    "postgresql": "PostgreSQL es una base de datos relacional avanzada, open source, conocida por su fiabilidad, escalabilidad y soporte de tipos de datos avanzados.",
    "api": "API (Application Programming Interface) es un conjunto de reglas que permiten que dos aplicaciones se comuniquen entre si.",
    "rest": "REST es un estilo de arquitectura para APIs web. Usa verbos HTTP (GET, POST, PUT, DELETE) y recursos identificados por URLs.",
    "json": "JSON (JavaScript Object Notation) es un formato ligero de intercambio de datos, facil de leer y escribir para humanos y maquinas.",
    "machine learning": "Machine Learning es una rama de la IA donde los sistemas aprenden automaticamente de datos sin ser programados explicitamente para cada tarea.",
    "inteligencia artificial": "La Inteligencia Artificial es la disciplina que crea sistemas capaces de realizar tareas que normalmente requieren inteligencia humana: razonar, aprender, entender lenguaje.",
    "deep learning": "Deep Learning es un subconjunto del Machine Learning que usa redes neuronales artificiales con muchas capas para aprender representaciones jerarquicas de los datos.",
    "redes neuronales": "Las redes neuronales son modelos computacionales inspirados en el cerebro humano. Constan de neuronas artificiales organizadas en capas que procesan informacion.",
    "css grid": "CSS Grid es un sistema de layout bidimensional que permite crear diseños complejos con filas y columnas de forma sencilla.",
    "flexbox": "Flexbox es un metodo de layout en CSS para distribuir y alinear elementos dentro de un contenedor, incluso cuando su tamaño es desconocido.",
    "sistema operativo": "Un sistema operativo es el software que gestiona el hardware y los recursos de una computadora. Ejemplos: Windows, macOS, Linux.",
    "linux": "Linux es un sistema operativo open source basado en Unix. Es la base de servidores, supercomputadoras, Android y muchos dispositivos.",
    "windows": "Windows es el sistema operativo de escritorio mas popular del mundo, desarrollado por Microsoft.",
    "algoritmo": "Un algoritmo es un conjunto finito de instrucciones o reglas paso a paso para resolver un problema o realizar una tarea.",
    "estructura de datos": "Las estructuras de datos son formas de organizar y almacenar datos en una computadora para que puedan ser accedidos y modificados eficientemente.",
    "ans ai": "ANS AI es un asistente virtual local creado por Aldrin Nicolas Salazar Avilas. Funciona con un motor de razonamiento local en Python/Flask, tiene memoria persistente y dos modos: Flask (razonamiento profundo) y Gapi (consultas rapidas).",
    "aldrin": "Aldrin Nicolas Salazar Avilas es el creador y desarrollador de ANS AI y del Proyecto ANS.",
    "proyecto ans": "El Proyecto ANS es una plataforma web educativa con asistente de IA integrado, juegos interactivos para aprender informatica y herramientas de aprendizaje.",
    "sass": "SASS es un preprocesador de CSS que agrega variables, anidamiento, mixins y funciones para escribir CSS mas organizado y mantenible.",
    "webpack": "Webpack es un bundler de JavaScript que empaleta todos los assets (JS, CSS, imagenes) en archivos optimizados para produccion.",
    "npm": "npm es el gestor de paquetes oficial de Node.js con el repositorio mas grande del mundo. Se usa para instalar y gestionar dependencias.",
    "vue": "Vue.js es un framework JavaScript progresivo para interfaces de usuario, conocido por su facilidad de aprendizaje y flexibilidad.",
    "angular": "Angular es un framework web completo de Google con TypeScript, ideal para proyectos grandes y empresariales.",
    "nextjs": "Next.js es un framework de React con SSR, SSG, y optimizaciones automaticas para sitios web rapidos y SEO-friendly.",
    "mongodb": "MongoDB es una base de datos NoSQL basada en documentos que guarda datos en formato BSON, ideal para datos flexibles.",
    "redis": "Redis es una base de datos en memoria ultra-rapida usada como cache, cola de mensajes y almacenamiento de sesiones.",
    "aws": "Amazon Web Services es la plataforma de cloud computing mas grande del mundo con mas de 200 servicios.",
    "flutter": "Flutter es un SDK de Google para crear apps moviles nativas para Android e iOS con un solo codigo fuente usando Dart.",
    "kotlin": "Kotlin es el lenguaje oficial para desarrollo Android, moderno y 100% interoperable con Java.",
    "swift": "Swift es el lenguaje de Apple para crear apps de iOS, macOS, watchOS y tvOS.",
    "rust": "Rust es un lenguaje de sistemas enfocado en seguridad, velocidad y concurrencia. Usado en Firefox, Docker y mas.",
    "go": "Go (Golang) es un lenguaje de Google disenado para simplicidad, eficiencia y concurrencia. Docker y Kubernetes estan hechos en Go.",
    "docker": "Docker es una plataforma de contenedorizacion que empaleta aplicaciones con todas sus dependencias en containers portables.",
    "kubernetes": "Kubernetes es una plataforma de orquestacion de containers que automatiza despliegue, escalado y gestion de apps.",
    "terraform": "Terraform es una herramienta de HashiCorp para infraestructura como codigo que permite crear y gestionar infraestructura en la nube.",
    "laravel": "Laravel es el framework PHP mas popular, elegante y con la mejor comunidad. Usa Eloquent ORM y Blade templates.",
    "ruby": "Ruby es un lenguaje elegante y orientado a objetos, conocido por Ruby on Rails para desarrollo web rapido.",
    "php": "PHP es un lenguaje del lado del servidor que powers el 77% de la web, incluyendo WordPress.",
    "babel": "Babel es un compilador de JavaScript que transforma codigo moderno en versiones compatibles con navegadores antiguos.",
}

CONVERSATION_CONTEXT = {
    "hola": [
        "Hola! Estoy listo para ayudarte. Puedo responder preguntas, resolver matematicas, explicar conceptos de programacion y mucho mas.",
        "Hola! Bienvenido. Mi motor de razonamiento esta activo. Escribe lo que necesites.",
        "Saludos! ANS AI a tu servicio. En que puedo ayudarte hoy?",
    ],
    "gracias": [
        "De nada! Siempre es un placer ayudarte.",
        "Para eso estamos! Si necesitas algo mas, aqui estoy.",
        "No hay de que! Preguntame lo que quieras.",
    ],
    "adios": [
        "Hasta luego! Fue un placer ayudarte. Vuelve cuando quieras.",
        "Nos vemos! Recuerda que estoy aqui cuando me necesites.",
        "Adios! Que tengas un excelente dia.",
    ],
    "buenos dias": [
        "Buenos dias! Espero que tengas un dia productivo. En que puedo ayudarte?",
        "Buenos dias! El dia esta perfecto para aprender algo nuevo. Preguntame!",
    ],
    "buenas tardes": [
        "Buenas tardes! Como puedo asistirte en esta tarde?",
        "Buenas tardes! Aqui estoy para lo que necesites.",
    ],
    "buenas noches": [
        "Buenas noches! Antes de descansar, hay algo que pueda ayudarte?",
        "Buenas noches! Estoy disponible si necesitas algo.",
    ],
}

GREETING_RESPONSES = {
    "como estas": "Funcionando al 100%! Todos mis modulos estan operativos. Tu como estas?",
    "que tal": "Todo excelente por aqui! Mis circuitos estan frescos y listos para trabajar.",
    "que onda": "Todo bien! Disparando neuronas a toda velocidad. Que necesitas?",
}

PERSONALITY_RESPONSES = {
    "que puedes hacer": (
        "Puedo muchas cosas!\n\n"
        "**Razonamiento:**\n"
        "- Que es [concepto]? -> Te explico que es, como funciona y para que sirve\n"
        "- Por que [fenomeno]? -> Te doy la explicacion con razonamiento\n"
        "- Cuales son las diferencias entre [X] y [Y] -> Comparo ambos\n"
        "- Dame un ejemplo de [tema] -> Ejemplos practicos\n"
        "- Es dificil [aprender X]? -> Te doy mi评估\n"
        "- Que lenguaje es mejor para [proposito]? -> Recomendaciones\n\n"
        "**Funciones:**\n"
        "- Matematicas: escribe operaciones como '25 + 17' o '3x + 5 = 20'\n"
        "- Fecha y hora: dime 'que hora es' o 'que fecha es'\n"
        "- Busqueda web: busco en Wikipedia si no se la respuesta\n"
        "- Aprendizaje: usa 'aprende: concepto = definicion'\n"
        "- Chistes: dime 'dame un chiste'"
    ),
    "ayuda": (
        "**Guia completa de ANS AI:**\n\n"
        "**Preguntas de razonamiento:**\n"
        "- `que es python?` -> Explicacion completa\n"
        "- `como funciona react?` -> Como funciona paso a paso\n"
        "- `por que el cielo es azul?` -> Razonamiento cientifico\n"
        "- `cuales son las diferencias entre Python y Java?` -> Comparacion\n"
        "- `dame un ejemplo de HTML` -> Ejemplos practicos\n"
        "- `es dificil aprender C++?` -> evaluacion de dificultad\n"
        "- `que lenguaje es mejor para web?` -> Recomendacion\n\n"
        "**Matematicas:**\n"
        "- `25 + 17` -> Operaciones basicas\n"
        "- `3x + 5 = 20` -> Ecuaciones con pasos\n"
        "- `20% de 500` -> Porcentajes\n"
        "- `raiz cuadrada de 144` -> Raices\n"
        "- `5!` -> Factorial\n\n"
        "**Otros:**\n"
        "- `que hora es` / `que fecha es`\n"
        "- `dame un chiste`\n"
        "- `aprende: concepto = definicion`"
    ),
}

TECH_JOKE = [
    "Por que los programadores prefieren el modo oscuro? Porque la luz atrae a los bugs!",
    "Cuanto tarda un programador en cambiar una bombilla? Ninguno, eso es problema de hardware!",
    "Un SQL entra a un bar, ve dos tablas y pregunta: puedo hacer un JOIN?",
    "Hay 10 tipos de personas: las que entienden binario y las que no.",
    "Por que JavaScript siempre se enfada? Porque no entiende las typeof!",
]

REASONING_ENGINE = {
    "que es": {
        "pattern": r"que\s+es\s+(.+?)[\?]?$/",
        "handler": "explain_concept",
    },
    "como funciona": {
        "pattern": r"como\s+funciona\s+(.+?)[\?]?$/",
        "handler": "explain_how",
    },
    "por que": {
        "pattern": r"por\s+que\s+(.+?)[\?]?$/",
        "handler": "explain_why",
    },
    "para que sirve": {
        "pattern": r"para\s+que\s+sirve\s+(.+?)[\?]?$/",
        "handler": "explain_purpose",
    },
    "cuales son las diferencias": {
        "pattern": r"cuales?\s+son?\s+(?:las?\s+)?diferencias?\s+entre\s+(.+?)\s+y\s+(.+?)[\?]?$/",
        "handler": "compare_things",
    },
    "que diferencia hay": {
        "pattern": r"que\s+diferencia\s+hay\s+entre\s+(.+?)\s+y\s+(.+?)[\?]?$/",
        "handler": "compare_things",
    },
    "ventajas": {
        "pattern": r"(?:cuales?\s+son?\s+)?(?:las?\s+)?ventajas?\s+(?:de|del)\s+(.+?)[\?]?$/",
        "handler": "list_pros",
    },
    "desventajas": {
        "pattern": r"(?:cuales?\s+son?\s+)?(?:las?\s+)?desventajas?\s+(?:de|del)\s+(.+?)[\?]?$/",
        "handler": "list_cons",
    },
    "ejemplo": {
        "pattern": r"(?:dame|pon|mustra|ense[nñ]ame)\s+(?:un\s+)?ejemplo\s+(?:de|del)\s+(.+?)[\?]?$/",
        "handler": "give_example",
    },
    "resumen": {
        "pattern": r"(?:dame|pon|haz)\s+(?:un\s+)?resumen\s+(?:de|sobre|del)\s+(.+?)[\?]?$/",
        "handler": "give_summary",
    },
    "es dificil": {
        "pattern": r"es\s+(?:dificil|complicado|complejo)\s+(?:aprender|entender|usar)\s+(.+?)[\?]?$/",
        "handler": "assess_difficulty",
    },
    "que lenguaje": {
        "pattern": r"(?:que|cual)\s+lenguaje\s+(?:de\s+programacion\s+)?(?:es\s+)?(?:mejor|ideal|bueno|recomendado)\s+(?:para|para\s+aprender|para\s+hacer)\s+(.+?)[\?]?$/",
        "handler": "recommend_language",
    },
    "cuanto vale": {
        "pattern": r"(?:cuanto\s+(?:vale|cuesta|precio))\s+(.+?)[\?]?$/",
        "handler": "check_price",
    },
    "pasos": {
        "pattern": r"(?:como\s+)?(?:puedo|hacer|puedo\s+hacer)\s+(.+?)(?:\s+paso\s+a\s+paso)?[\?]?$/",
        "handler": "step_by_step",
    },
}

REASONING_PATTERNS = [
    (r"^que\s+es\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+un\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+una\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+el\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+la\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+los\s+(.+?)[\?\s]*$", "what_is"),
    (r"^que\s+es\s+las\s+(.+?)[\?\s]*$", "what_is"),
    (r"^como\s+funciona\s+(.+?)[\?\s]*$", "how_works"),
    (r"^como\s+se\s+usa\s+(.+?)[\?\s]*$", "how_use"),
    (r"^como\s+(?:puedo|puedo)\s+(.+?)[\?\s]*$", "how_to"),
    (r"^por\s+que\s+(.+?)[\?\s]*$", "why"),
    (r"^para\s+que\s+(?:sirve|sirve)\s+(.+?)[\?\s]*$", "purpose"),
    (r"^cuales?\s+son?\s+(?:las?\s+)?ventajas?\s+(?:de|del)\s+(.+?)[\?\s]*$", "pros"),
    (r"^cuales?\s+son?\s+(?:las?\s+)?desventajas?\s+(?:de|del)\s+(.+?)[\?\s]*$", "cons"),
    (r"^(?:dame|pon|mustra)\s+(?:un\s+)?ejemplo\s+(?:de|del)\s+(.+?)[\?\s]*$", "example"),
    (r"^(?:dame|pon|haz)\s+(?:un\s+)?resumen\s+(?:de|sobre|del)\s+(.+?)[\?\s]*$", "summary"),
    (r"^(?:cuales?\s+son?\s+)?(?:las?\s+)?diferencias?\s+entre\s+(.+?)\s+y\s+(.+?)[\?\s]*$", "differences"),
    (r"^que\s+diferencia\s+hay\s+entre\s+(.+?)\s+y\s+(.+?)[\?\s]*$", "differences"),
    (r"^es\s+(.+?)\s+(?:dificil|complicado|complejo|facil|rapido|lento)[\?\s]*$", "difficulty"),
    (r"^(?:que\s+tan\s+)?(?:dificil|complicado|complejo|facil)\s+(?:es\s+)?(?:aprender|entender|usar|hacer)\s+(.+?)[\?\s]*$", "difficulty"),
    (r"^(?:cual|que)\s+lenguaje\s+(?:es\s+)?(?:mejor|ideal|bueno|recomendado)\s+(?:para|para\s+aprender|para\s+hacer)\s+(.+?)[\?\s]*$", "recommend"),
    (r"^(?:como\s+)?(?:puedo|puedo)\s+(.+?)\s+paso\s+a\s+paso[\?\s]*$", "step_by_step"),
]

WHY_RESPONSES = {
    "el cielo es azul": "El cielo es azul por un fenomeno llamado **dispersion de Rayleigh**. La luz del sol viaja en todas las longitudes de onda. Cuando entra en la atmosfera, las moleculas de gas esparcen mas la luz azul (longitud de onda corta) que la luz roja. Por eso vemos el cielo de color azul desde la superficie de la Tierra.",
    "la tierra gira": "La Tierra gira por la conservacion del momento angular del disco protoplanetario original que formo el Sistema Solar hace 4,600 millones de anos. No hay 'freno' significativo en el espacio vacio, asi que sigue girando.",
    "llueve": "La lluvia se forma por el ciclo del agua: el sol calienta el agua de oceanos y rios, que se evapora y sube como vapor. En la atmosfera alta, el vapor se enria y forma nubes de gotas de agua o cristales de hielo. Cuando estas gotas se vuelven pesadas, caen por gravedad como lluvia.",
    "la gravedad existe": "La gravedad es una fuerza fundamental descrita por Newton y mejor explicada por Einstein. Segun la relatividad general, la masa curva el espacio-tiempo a su alrededor, y otros objetos se mueven siguiendo esas curvas.",
    "el sonido se propaga": "El sonido es una onda mecanica que viaja vibrando las moleculas del medio (aire, agua, solidos). Cuando un objeto vibra, comprime y descomprime el aire a su alrededor, creando ondas de presion que viajan a approx. 343 m/s en el aire a 20 grados C.",
    "las plantas son verdes": "Las plantas son verdes porque contienen clorofila, el pigmento que usan para la fotosintesis. La clorofila absorbe la luz roja y azul del espectro solar, pero refleja la luz verde, que es la que vemos.",
    "internet funciona": "Internet funciona mediante una red global de cables (fibra optica), routers y servidores. Los datos se dividen en paquetes, viajan por la red usando protocolos TCP/IP, y se reensamblan en el destino.",
    "los coches funcionan": "Los coches de combustion interna convierten energia quimica (gasolina) en energia mecanica. La mezcla de gasolina y aire se comprime y explode en los cilindros, moviendo los pistones que giran el ciguenal, que transmite la fuerza a las ruedas.",
}

DIFFICULTY_MAP = {
    "python": "Python es considerado uno de los lenguajes **mas faciles de aprender**. Su sintaxis es clara y similar al ingles. Con dedicacion, puedes aprender lo basico en 2-4 semanas.",
    "javascript": "JavaScript es **moderadamente facil** de empezar pero tiene conceptos complejos como closures, event loop y async/await. Lo basico se aprende en 2-4 semanas.",
    "java": "Java es **moderadamente dificil** por su verbosidad y conceptos de orientacion a objetos estricta.",
    "c++": "C++ es **dificil**. Tiene punteros, gestion de memoria manual, y una sintaxis compleja.",
    "react": "React es **moderadamente dificil**. Requiere saber JavaScript bien. Los conceptos de JSX, hooks y estado pueden confundir al principio.",
    "flask": "Flask es **facil** de aprender si ya sabes Python. La curva de aprendizaje es suave y la documentacion es excelente.",
    "docker": "Docker basico es **facil**. El networking y orquestacion con Kubernetes son **dificiles**.",
    "kubernetes": "Kubernetes es **dificil**. Requiere saber Docker, redes, y sistemas distribuidos.",
    "git": "Git basico es **facil**. Los conflictos de merge y operaciones avanzadas como rebasing son **dificiles**.",
    "sql": "SQL basico es **muy facil**. Las consultas complejas con JOINs y optimizacion son **moderadamente dificiles**.",
    "linux": "Linux basico es **accesible**. La linea de comandos puede intimidar pero es **muy util** una vez que la aprendes.",
    "machine learning": "ML es **dificil**. Requiere programacion, estadistica y algebra lineal.",
    "deep learning": "Deep Learning es **muy dificil**. Especializate despues de dominar ML basico.",
    "html": "HTML es **el mas facil de todos**. Es solo estructura, sin logica. Se aprende en pocos dias.",
    "css": "CSS es **facil de empezar** pero **dificil de dominar**. Los layouts responsivos y animaciones avanzadas requieren practica.",
}

IMAGE_DB = {
    "python": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
    "javascript": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    "html": "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
    "css": "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
    "gato": "https://cdn.pixabay.com/photo/2017/02/20/18/03/cat-2083492_1280.jpg",
    "perro": "https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313_1280.jpg",
    "tierra": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/1280px-The_Earth_seen_from_Apollo_17.jpg",
    "luna": "https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg",
    "sol": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Solar_prominence_20930215.jpg/1280px-Solar_prominence_20930215.jpg",
    "linux": "https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png",
    "windows": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Windows_logo_-_2012.svg",
    "apple": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    "google": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    "titanic": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/RMS_Titanic_3.jpg/1280px-RMS_Titanic_3.jpg",
    "coliseo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseum_in_Rome_2015.jpg/1280px-Colosseum_in_Rome_2015.jpg",
    "piramides": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1280px-Kheops-Pyramid.jpg",
    "marte": "https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg",
    "jupiter": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
    "bitcoin": "https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg",
    "minecraft": "https://upload.wikimedia.org/wikipedia/commons/3/32/Minecraft_logo.svg",
    "disney": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Disney_wordmark.svg",
    "coca cola": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Coca-Cola_logo.svg",
    "taj mahal": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Taj_Mahal_in_Agro.jpg/1280px-Taj_Mahal_in_Agro.jpg",
    "nintendo": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Nintendo.svg",
    "spotify": "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg",
    "netflix": "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    "tesla": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Tesla_Motors_logo.svg",
    "spacex": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/SpaceX_logo_black.svg/1280px-SpaceX_logo_black.svg.png",
    "robot": "https://upload.wikimedia.org/wikipedia/commons/4/4c/ASIMO_%28roboter%29.jpg",
    "delfin": "https://cdn.pixabay.com/photo/2013/12/21/15/33/dolphin-231869_1280.jpg",
    "elefante": "https://cdn.pixabay.com/photo/2016/11/14/04/45/elephant-1822636_1280.jpg",
    "leon": "https://cdn.pixabay.com/photo/2017/02/28/19/34/lion-2106603_1280.jpg",
    "giraffe": "https://cdn.pixabay.com/photo/2017/02/24/25/giraffe-2094770_1280.jpg",
}

FACTS_DB = {
    "python": "Python fue creado por Guido van Rossum en 1991. Su nombre viene de los Monty Python.",
    "javascript": "JavaScript fue creado por Brendan Eich en 10 dias en 1995.",
    "html": "HTML fue creado por Tim Berners-Lee en 1991 mientras trabajaba en el CERN.",
    "google": "Google procesa mas de 40,000 busquedas por segundo, mas de 3.5 billones al dia.",
    "internet": "El primer sitio web fue creado por Tim Berners-Lee en 1991 y aun esta online.",
    "linux": "Linux fue creado por Linus Torvalds en 1991 como un proyecto hobby.",
    "windows": "Windows 1.0 fue lanzado en 1985, no fue popular hasta Windows 3.0 en 1990.",
    "amazon": "Amazon empezo vendiendo libros en 1994 desde el garaje de Jeff Bezos.",
    "gato": "Los gatos domesticos comparten el 95.6% de su genoma con los tigres.",
    "perro": "Los perros tienen aproximadamente 300 millones de receptores olfativos, comparado con 5 millones en humanos.",
    "delfin": "Los delfines duermen con un ojo abierto y la mitad de su cerebro activo.",
    "pulpo": "Los pulpos tienen tres corazones, sangre azul y nueve cerebros (uno central y ocho en los brazos).",
    "abeja": "Una abeja produce aproximadamente una cucharadita de miel en toda su vida.",
    "ballena": "La ballena azul es el animal mas grande que ha existido, pesando hasta 200 toneladas.",
    "tierra": "La Tierra viaja alrededor del Sol a 107,000 km/h, pero no lo sentimos por la inercia.",
    "luna": "La Luna se aleja de la Tierra unos 3.8 cm cada año.",
    "sol": "El Sol produce energia equivalente a 100 mil millones de bombas de hidrogeno por segundo.",
    "agua": "El agua cubre el 71% de la superficie de la Tierra, pero solo el 2.5% es agua dulce.",
    "cuerpo humano": "El cuerpo humano tiene aproximadamente 60,000 kilometros de vasos sanguineos.",
    "cerebro": "El cerebro humano tiene alrededor de 86 mil millones de neuronas.",
    "dna": "El ADN humano tiene aproximadamente 3 mil millones de pares de bases.",
    "microondas": "El horno microondas fue inventado por accidente en 1945 por Percy Spencer mientras trabajaba con radar.",
    "youtube": "YouTube fue creado por tres ex-empleados de PayPal en 2005 y el primer video se llamo 'Me at the zoo'.",
    "facebook": "Facebook fue lanzado en 2004 por Mark Zuckerberg desde su habitacion en Harvard.",
    "whatsapp": "WhatsApp fue comprado por Facebook en 2014 por $19 mil millones.",
    "wikipedia": "Wikipedia tiene mas de 60 millones de articulos en mas de 300 idiomas.",
    "tesla": "Tesla fue fundada en 2003 por Martin Eberhard y Marc Tarpenning. Elon Musk se unio como inversor principal.",
    "spacex": "SpaceX fue fundada por Elon Musk en 2002 con el objetivo de colonizar Marte.",
    "nasa": "La NASA fue creada en 1958 en respuesta al lanzamiento del Sputnik por la Union Sovietica.",
    "apple": "Apple fue fundada por Steve Jobs, Steve Wozniak y Ronald Wayne en 1976 en un garaje.",
    "microsoft": "Microsoft fue fundada por Bill Gates y Paul Allen en 1975.",
    "netflix": "Netflix empezo en 1997 como un servicio de alquiler de DVD por correo.",
    "spotify": "Spotify fue lanzado en 2008 en Suecia y revoluciono la industria musical con streaming.",
    "chatgpt": "ChatGPT fue lanzado por OpenAI en noviembre de 2022 y alcanzo 100 millones de usuarios en solo 2 meses.",
    "android": "Android fue comprado por Google en 2005 por $50 millones.",
    "iphone": "El primer iPhone fue lanzado en 2007 por Steve Jobs y cambio la industria de los smartphones.",
    "bitcoin": "Bitcoin fue creado en 2009 por una persona o grupo bajo el seudonimo Satoshi Nakamoto.",
    "ia": "El termino 'Inteligencia Artificial' fue acunado por John McCarthy en 1956 en la Conferencia de Dartmouth.",
    "robot": "La palabra 'robot' viene del checo 'robota' que significa 'trabajo forzado'.",
    "programacion": "El primer lenguaje de programacion de alto nivel fue Plankalkul, creado por Konrad Zuse entre 1942 y 1945.",
    "primer ordenador": "La ENIAC, considerada la primera computadora electronica de proposito general, pesaba 27 toneladas.",
    "ibm": "IBM existe desde 1911, originalmente como Computing-Tabulating-Recording Company (CTR).",
    "bug": "El termino 'bug' en programacion viene de un insecto real encontrado en un relay del Harvard Mark II en 1947.",
    "hacker": "El termino 'hacker' originalmente describia a programadores expertos, no a criminales informaticos.",
    "contraseña": "La contraseña mas comun en el mundo es '123456', seguida de 'password'.",
    "velocidad luz": "La luz viaja a 299,792,458 metros por segundo. Puede dar 7.5 vueltas a la Tierra en un segundo.",
    "gravedad": "La gravedad es la fuerza mas debil de las cuatro fuerzas fundamentales, pero la que mas sentimos.",
    "rayo": "Un rayo puede alcanzar temperaturas de 30,000 grados Celsius.",
    "formula 1": "Un coche de Formula 1 puede perder hasta 10 kg de peso durante una carrera por el desgaste de los neumaticos.",
    "ajedrez": "Hay mas posibles partidas de ajedrez que atomos en el universo observable.",
    "musica": "La cancion mas reproducida en Spotify es 'Blinding Lights' de The Weeknd, con mas de 4 mil millones de reproducciones.",
    "coliseo": "El Coliseo Romano podia albergar hasta 80,000 espectadores y tenia un toldo retractil gigante (velarium).",
    "piramides": "Las piramides de Egipto fueron construidas hace mas de 4,500 anos y son las unicas maravillas del mundo antiguo que aun existen.",
    "marte": "Un dia en Marte dura 24 horas y 37 minutos, casi igual que un dia en la Tierra.",
    "jupiter": "Jupiter es el planeta mas grande del sistema solar y su Gran Mancha Roja es una tormenta que dura siglos.",
    "vuelo": "El primer vuelo comercial de pasajeros fue en 1914, volando de San Petersburgo a Tampa, Florida, y duro 23 minutos.",
    "titanic": "El Titanic tenia 269 metros de eslora y se hundio en 1912 en su viaje inaugural.",
    "the beatles": "Los Beatles vendieron mas de 600 millones de discos en todo el mundo.",
    "star wars": "Star Wars fue estrenada en 1977 y recaudo $775 millones, superando a Tiburon como la pelicula mas taquillera.",
    "minecraft": "Minecraft es el videojuego mas vendido de la historia con mas de 300 millones de copias.",
    "gta": "Grand Theft Auto V es uno de los juegos mas exitosos, generando mas de $6 mil millones desde su lanzamiento en 2013.",
    "pokemon": "Pokemon es la franquicia mediatica mas grande del mundo, superando a Mickey Mouse y Star Wars.",
    "coca cola": "Coca-Cola fue inventada en 1886 por John Pemberton y originalmente contenia cocaina.",
    "kfc": "KFC fue fundado por el Coronel Harland Sanders a los 65 años, despues de recibir su primer cheque de jubilacion.",
    "mcdonalds": "McDonald's fue fundado en 1940 por los hermanos Richard y Maurice McDonald en San Bernardino, California.",
    "lego": "LEGO viene del danes 'leg godt' que significa 'juega bien'. Las piezas actuales son compatibles con las de 1958.",
    "disney": "Walt Disney fundo Disney en 1923. El primer personaje creado fue Oswald el Conejo Afortunado, no Mickey Mouse.",
    "nintendo": "Nintendo fue fundada en 1889 como una empresa de naipes (hanafuda) antes de entrar en los videojuegos.",
    "samsung": "Samsung empezo en 1938 como una empresa de exportacion de pescado y verduras en Corea del Sur.",
    "honda": "Honda empezo fabricando motores para bicicletas despues de la Segunda Guerra Mundial.",
    "toyota": "Toyota empezo como fabricante de telares automaticos antes de producir automoviles.",
    "ferrari": "Ferrari fue fundada por Enzo Ferrari en 1947. Originalmente era el equipo de carreras de Alfa Romeo.",
    "lamborghini": "Lamborghini fue fundada por Ferruccio Lamborghini, un fabricante de tractores, despues de una disputa con Enzo Ferrari.",
    "nikon": "Nikon fue fundada en 1917 como Nippon Kogaku Kogyo, fabricando lentes opticos para camaras.",
    "canon": "Canon fue fundada en 1937 como Precision Optical Industry. Su primera camara fue la Kwanon.",
    "post it": "Las notas Post-it fueron inventadas por accidente en 1968 cuando Spencer Silver creo un adhesivo debil.",
    "velcro": "El velcro fue inventado en 1941 por George de Mestral despues de observar como las semillas de cardo se pegaban a su ropa.",
    "rayos x": "Los rayos X fueron descubiertos por Wilhelm Rontgen en 1895. La primera radiografia fue de la mano de su esposa.",
    "penicilina": "La penicilina fue descubierta por Alexander Fleming en 1928 cuando observo moho que mataba bacterias.",
    "vacuna": "La primera vacuna fue creada por Edward Jenner en 1796 contra la viruela.",
    "relatividad": "Einstein publico su teoria de la relatividad general en 1915, prediciendo agujeros negros y ondas gravitacionales.",
    "big bang": "La teoria del Big Bang fue propuesta por Georges Lemaitre en 1927, un sacerdote y astronomo belga.",
    "agujero negro": "El primer agujero negro fotografiado (M87) fue capturado en 2019 por el telescopio Event Horizon.",
    "fotosintesis": "La fotosintesis convierte la luz solar en energia quimica, produciendo oxigeno como subproducto.",
    "mariposa": "Las mariposas saborean con sus patas y tienen sensores de sabor en sus pies.",
    "camaleon": "Los camaleones cambian de color para comunicarse y regular temperatura, no solo para camuflarse.",
    "colibri": "Los colibris son las unicas aves que pueden volar hacia atras y baten sus alas hasta 80 veces por segundo.",
    "hormiga": "Las hormigas pueden levantar hasta 50 veces su propio peso y existen mas de 12,000 especies.",
    "elefante": "Los elefantes son los unicos animales con cuatro rodillas. Son el animal terrestre mas grande.",
    "jirafa": "Las jirafas tienen el mismo numero de vertebras en el cuello que los humanos: siete.",
    "canguro": "Los canguros no pueden caminar hacia atras y las hembras tienen tres vaginas.",
    "panda": "Los pandas gigantes pasan hasta 14 horas al dia comiendo bambu, hasta 38 kg diarios.",
    "tiburon": "Los tiburones han existido por mas de 400 millones de anos, antes que los dinosaurios.",
    "fuego": "El fuego no tiene sombra porque la luz lo atraviesa. El fuego es plasma, no gas.",
    "hielo": "El hielo flota porque es menos denso que el agua liquida, una propiedad unica del agua.",
    "imanes": "Los imanes tienen dos polos (norte y sur) que nunca se pueden separar, incluso si los partes.",
    "eco": "El eco se produce cuando el sonido rebota en una superficie y tarda mas de 0.1 segundos en regresar.",
    "arcoiris": "Los arcoiris son circulos completos, pero desde el suelo solo vemos un arco porque la tierra bloquea la mitad.",
}

CONCEPT_DB = {
    "python": {
        "what": "Python es un lenguaje de programacion de alto nivel, interpretado y multiparadigma. Fue creado por Guido van Rossum en 1991.",
        "how": "Python se ejecuta mediante un interpretador que lee el codigo linea por linea y lo convierte en bytecode, que luego se ejecuta en la maquina virtual de Python.",
        "why": "Python se usa porque su sintaxis es clara y facil de leer, tiene una enorma cantidad de librerias, y sirve para casi todo: web, IA, datos, automatizacion.",
        "purpose": "Python sirve para crear aplicaciones web, analizar datos, crear inteligencia artificial, automatizar tareas, y mucho mas.",
        "examples": ["print('Hola Mundo') - imprime texto", "for i in range(10): print(i) - imprime del 0 al 9", "def saludar(nombre): return f'Hola {nombre}' - define una funcion"],
        "difficulty": "Python es uno de los lenguajes mas faciles de aprender. Su sintaxis es similar al ingles y tiene mucha documentacion.",
        "languages_used_for": ["web (Django, Flask)", "ciencia de datos (Pandas, NumPy)", "IA (TensorFlow, PyTorch)", "automatizacion", "juegos (Pygame)"],
    },
    "javascript": {
        "what": "JavaScript es un lenguaje de programacion interpretado, orientado a eventos y multiparadigma. Es el lenguaje de la web.",
        "how": "JavaScript se ejecuta en el navegador (frontend) o en Node.js (backend). Usa un motor de ejecucion (V8 en Chrome) que compila el codigo a bytecode optimizado.",
        "why": "JavaScript es esencial para la web interactiva. Casi todas las paginas web lo usan, y con Node.js tambien sirve para el backend.",
        "purpose": "JavaScript sirve para hacer paginas web interactivas, aplicaciones de escritorio (Electron), servidores (Node.js), y apps moviles (React Native).",
        "examples": ["console.log('Hola Mundo') - imprime en consola", "document.getElementById('app').innerHTML = 'Hola' - cambia contenido HTML", "fetch('https://api.datos.com').then(r => r.json()) - hace peticiones HTTP"],
        "difficulty": "JavaScript es relativamente facil de empezar, pero tiene conceptos complejos como el event loop, closures y async/await que requieren practica.",
        "languages_used_for": ["web frontend (React, Vue, Angular)", "web backend (Node.js, Express)", "apps de escritorio (Electron)", "apps moviles (React Native)"],
    },
    "html": {
        "what": "HTML (HyperText Markup Language) es el lenguaje de marcado que define la estructura y el contenido de las paginas web.",
        "how": "HTML usa etiquetas como <div>, <p>, <h1> para crear una estructura jerarquica. El navegador lee estas etiquetas y renderiza el contenido visualmente.",
        "why": "HTML es la base de toda pagina web. Sin HTML no habria contenido en internet. Es el esqueleto sobre el que se aplica CSS (diseño) y JavaScript (logica).",
        "purpose": "HTML sirve para estructurar contenido web: textos, imagenes, videos, formularios, enlaces y mas.",
        "examples": ["<h1>Mi Titulo</h1> - titulo principal", "<p>Texto parrafo</p> - parrafo de texto", "<a href='https://google.com'>Ir a Google</a> - enlace"],
        "difficulty": "HTML es el lenguaje mas facil de aprender en web. No logica, solo estructura.",
    },
    "css": {
        "what": "CSS (Cascading Style Sheets) es el lenguaje que controla la apariencia visual de las paginas web: colores, fuentes, espaciado, layout y animaciones.",
        "how": "CSS se aplica a elementos HTML usando selectores. El navegador combina todas las reglas CSS y las aplica al DOM para crear el diseño visual final.",
        "why": "Sin CSS, las paginas web serian solo texto negro sobre fondo blanco. CSS permite crear diseños atractivos, responsivos y modernos.",
        "purpose": "CSS sirve para dar estilo a las paginas web: colores, tipografia, layouts con Flexbox/Grid, animaciones, y diseno responsivo para movil.",
        "examples": ["body { background: #000; color: white; } - fondo negro, texto blanco", ".boton { border-radius: 8px; padding: 10px; } - estilos de boton", "@media (max-width: 600px) { .nav { display: none; } } - ocultar nav en movil"],
        "difficulty": "CSS es facil de empezar pero dificil de dominar. Los layouts responsivos y las animaciones avanzadas requieren practica.",
    },
    "flask": {
        "what": "Flask es un microframework web para Python. Permite crear aplicaciones web y APIs de forma ligera y flexible.",
        "how": "Flask recibe peticiones HTTP, las enruta a funciones Python (views), y retorna respuestas (HTML, JSON, etc). Usa Werkzeug para HTTP y Jinja2 para templates.",
        "why": "Flask es ideal para aprender web con Python porque es simple, no impone estructura, y te da libertad total de elegir tus herramientas.",
        "purpose": "Flask sirve para crear APIs REST, paginas web, dashboards, microservicios, y prototipos rapidos.",
        "examples": ["@app.route('/') def home(): return 'Hola' - ruta basica", "@app.route('/api', methods=['POST']) - endpoint POST", "app.run(debug=True) - inicia el servidor"],
        "difficulty": "Flask es facil de aprender si ya sabes Python basico. La curva de aprendizaje es suave.",
    },
    "react": {
        "what": "React es una libreria JavaScript de Meta (Facebook) para construir interfaces de usuario con componentes reutilizables.",
        "how": "React usa un Virtual DOM que compara el estado anterior con el nuevo y solo actualiza lo que cambio en el DOM real, haciendolo muy eficiente.",
        "why": "React facilita crear UIs complejas dividiendolas en componentes independientes. Tiene un ecosistema enorme: Next.js, React Native, etc.",
        "purpose": "React sirve para crear interfaces de usuario interactivas: SPAs, dashboards, apps moviles (React Native), y sitios web (Next.js).",
        "examples": ["function App() { return <h1>Hola</h1> } - componente basico", "const [count, setCount] = useState(0) - estado local", "<App /> - renderizar componente"],
        "difficulty": "React requiere saber JavaScript bien. Los conceptos de JSX, hooks y estado pueden ser confusos al principio.",
    },
    "git": {
        "what": "Git es un sistema de control de versiones distribuido creado por Linus Torvalds en 2005. Registra cambios en archivos a lo largo del tiempo.",
        "how": "Git guarda snapshots del codigo en un repositorio local. Puedes crear ramas, hacer commits, y sincronizar con repositorios remotos como GitHub.",
        "why": "Git es esencial para trabajar en equipo sin pisarse el codigo. Permite revertir cambios, comparar versiones, y colaborar de forma segura.",
        "purpose": "Git sirve para versionar codigo, colaborar en equipo, mantener historial de cambios, y integrar con GitHub/GitLab.",
        "examples": ["git init - crea un repositorio nuevo", "git add . && git commit -m 'mensaje' - guarda cambios", "git push origin main - sube al servidor"],
        "difficulty": "Git basico es facil. Los conflictos de merge y el rebasing son lo mas complicado.",
    },
    "sql": {
        "what": "SQL (Structured Query Language) es el lenguaje estandar para gestionar y consultar bases de datos relacionales.",
        "how": "SQL envia declaraciones a la base de datos: CREATE para tablas, INSERT para datos, SELECT para consultar, UPDATE para modificar, DELETE para borrar.",
        "why": "SQL es la forma estandar de interactuar con bases de datos. Casi toda informacion de internet esta guardada en bases de datos consultadas con SQL.",
        "purpose": "SQL sirve para crear, consultar, modificar y eliminar datos en bases de datos como MySQL, PostgreSQL, SQLite, SQL Server.",
        "examples": ["SELECT * FROM usuarios WHERE edad > 18 - buscar mayores de 18", "INSERT INTO usuarios (nombre, email) VALUES ('Ana', 'ana@mail.com') - agregar registro", "UPDATE usuarios SET nombre = 'Ana M.' WHERE id = 1 - modificar dato"],
        "difficulty": "SQL basico es muy facil. Las consultas complejas con JOINs, subconsultas y optimizacion requieren mas practica.",
    },
    "linux": {
        "what": "Linux es un sistema operativo open source basado en Unix, creado por Linus Torvalds en 1991. Es la base de la mayoria de servidores del mundo.",
        "how": "Linux usa un kernel que gestiona el hardware. Las distribuciones (Ubuntu, Fedora, etc.) empaquetan el kernel con herramientas como el shell, gestor de paquetes, y entorno de escritorio.",
        "why": "Linux es gratuito, seguro, estable, y personalizable. Es el SO preferido para servidores, supercomputadoras, y desarrolladores.",
        "purpose": "Linux sirve para servidores web, desarrollo de software, ciencia de datos, IoT, y como sistema de escritorio alternativo.",
        "examples": ["ls - listar archivos", "cd /home - cambiar directorio", "sudo apt install python3 - instalar paquete"],
        "difficulty": "Linux basico es accesible. La linea de comandos puede intimidar al principio pero es muy poderosa.",
    },
    "inteligencia artificial": {
        "what": "La Inteligencia Artificial es la disciplina de la computacion que crea sistemas capaces de realizar tareas que normalmente requieren inteligencia humana.",
        "how": "La IA usa algoritmos de machine learning que aprenden patrones en datos. Las redes neuronales artificiales simulan el cerebro humano con capas de neuronas que procesan informacion.",
        "why": "La IA existe para automatizar tareas complejas, encontrar patrones en grandes volumes de datos, y crear sistemas que se adapten y mejoren solos.",
        "purpose": "La IA sirve para asistentes virtuales (como yo!), recomendaciones (Netflix, Spotify), coches autonomos, diagnostico medico, traduccion, y mucho mas.",
        "examples": ["ChatGPT y asistentes de voz - procesamiento de lenguaje natural", "Reconocimiento facial en fotos - vision por computadora", "Autocompletar en Google - prediccion de texto"],
        "difficulty": "La IA requiere bases solidas de programacion, matematicas y estadistica. Es un campo amplio pero muy interesante.",
    },
    "machine learning": {
        "what": "Machine Learning es una rama de la IA donde los sistemas aprenden automaticamente de datos sin ser programados explicitamente para cada tarea.",
        "how": "ML usa algoritmos que analizan datos, encuentran patrones, y crean modelos que pueden hacer predicciones o decisiones sobre datos nuevos.",
        "why": "ML permite resolver problemas donde programar reglas explicitas es imposible o muy complejo, como reconocer imagenes o entender texto.",
        "purpose": "ML sirve para clasificacion de datos, prediccion, recomendaciones, deteccion de fraude, procesamiento de lenguaje natural, y mas.",
        "examples": ["Spotify te recomienda musica basado en tu historial", "Gmail detecta spam analizando patrones de emails", "Netflix predice que peliculas te gustarian"],
        "difficulty": "ML requiere saber programacion (Python), matematicas (algebra, estadistica), y conceptos de algoritmos.",
    },
    "deep learning": {
        "what": "Deep Learning es un subconjunto del Machine Learning que usa redes neuronales artificiales con muchas capas (profundas) para aprender representaciones jerarquicas de los datos.",
        "how": "Las redes profundas tienen multiples capas ocultas. Cada capa aprende caracteristicas mas abstractas: bordes -> formas -> objetos -> escenas.",
        "why": "Deep Learning ha revolucionado la IA porque puede aprender automaticamente caracteristicas complejas de datos no estructurados como imagenes, audio y texto.",
        "purpose": "Deep Learning sirve para reconocimiento de imagenes, procesamiento de lenguaje natural, coches autonomos, generacion de texto/imagenes, y mas.",
        "examples": ["ChatGPT usa transformers (redes profundas) para generar texto", "Los filtros de Instagram usan redes neuronales para detectar caras", "Tesla usa deep learning para que los coches 'vean' la carretera"],
        "difficulty": "Deep Learning es de los campos mas complejos. Requiere saber programacion, matematicas avanzadas, y tener conocimiento de arquitecturas de redes.",
    },
    "nodejs": {
        "what": "Node.js es un entorno de ejecucion de JavaScript fuera del navegador. Permite crear servidores, APIs y herramientas de linea de comandos en JavaScript.",
        "how": "Node.js usa el motor V8 de Google Chrome para ejecutar JavaScript en el servidor. Usa un event loop no-bloqueante que lo hace muy eficiente para operaciones de E/S.",
        "why": "Node.js permite usar un solo lenguaje (JavaScript) tanto para frontend como backend, reduciendo la complejidad del desarrollo fullstack.",
        "purpose": "Node.js sirve para crear servidores web, APIs REST/GraphQL, herramientas CLI, automatizacion (Gulp, Webpack), y aplicaciones en tiempo real (chats, juegos).",
        "examples": ["const http = require('http'); - servidor basico", "express.get('/api', (req, res) => res.json({ok: true})) - API con Express", "npm install paquete - instalar dependencias"],
        "difficulty": "Node.js es accesible si sabes JavaScript. Los conceptos de async/await y event loop son los mas complicados.",
    },
    "github": {
        "what": "GitHub es la plataforma de hosting de repositorios Git mas grande del mundo. Ofrece herramientas de colaboracion, CI/CD, y gestion de proyectos.",
        "how": "GitHub almacena repositorios Git en la nube. Los desarrolladores suben (push) y descargan (pull) codigo, crean ramas (branches), y fusionan cambios (merge).",
        "why": "GitHub es esencial para colaborar en equipo. Permite revisar codigo (pull requests), reportar errores (issues), y automatizar pruebas (Actions).",
        "purpose": "GitHub sirve para hospedar codigo, colaborar en proyectos, documentar con READMEs, y automatizar flujos de trabajo de desarrollo.",
        "examples": ["git push origin main - sube codigo a GitHub", "Pull Request - proponer cambios para revision", "GitHub Actions - CI/CD automatico"],
        "difficulty": "GitHub basico es facil (push, pull, issues). Los flujos de trabajo avanzados (rebasing, cherry-pick, Actions) requieren mas practica.",
    },
    "docker": {
        "what": "Docker es una plataforma de contenedorizacion que empaleta aplicaciones con todas sus dependencias en containers portables.",
        "how": "Docker crea containers aislados que incluyen la app, librerias, y configuracion. Los containers corren igual en cualquier maquina con Docker instalado.",
        "why": "Docker resuelve el problema de 'en mi maquina funciona'. Asegura que la app se ejecute igual en desarrollo, testing y produccion.",
        "purpose": "Docker sirve para empaquetar aplicaciones, crear ambientes de desarrollo reproducibles, y desplegar en la nube de forma consistente.",
        "examples": ["docker build -t mi-app . - crear imagen Docker", "docker run -p 5000:5000 mi-app - ejecutar container", "docker-compose up - levantar multiples servicios"],
        "difficulty": "Docker basico es entendible. El networking, volumes y orquestacion (Kubernetes) son mas complejos.",
    },
    "kubernetes": {
        "what": "Kubernetes (K8s) es una plataforma open source de orquestacion de containers que automatiza el despliegue, escalado y gestion de aplicaciones.",
        "how": "Kubernetes gestiona clusters de machines (nodos). Organiza containers en Pods, los distribuye, los balancea carga, y los reinicia si fallan.",
        "why": "Kubernetes permite gestionar miles de containers en produccion de forma automatica. Es el estandar de la industria para aplicaciones cloud-native.",
        "purpose": "Kubernetes sirve para desplegar, escalar y gestionar aplicaciones containerizadas en produccion de forma automatica y confiable.",
        "examples": ["kubectl apply -f deployment.yaml - desplegar app", "kubectl scale --replicas=5 deployment/mi-app - escalar a 5 instancias", "kubectl get pods - ver pods corriendo"],
        "difficulty": "Kubernetes es complejo. Requiere saber Docker bien, y conceptos de redes, storage, y sistemas distribuidos.",
    },
    "typescript": {
        "what": "TypeScript es un superconjunto de JavaScript que agrega tipos estaticos. Fue creado por Microsoft para hacer el JS mas robusto.",
        "how": "TypeScript agrega un sistema de tipos sobre JavaScript. El compilador TS verifica tipos en tiempo de desarrollo y genera JavaScript vanilla que ejecuta el navegador.",
        "why": "TypeScript previene errores comunes de JavaScript (como llamar una funcion con el tipo de dato incorrecto) y hace el codigo mas mantenible.",
        "purpose": "TypeScript sirve para escribir JavaScript mas seguro y escalable, especialmente en proyectos grandes y en equipo.",
        "examples": ["let nombre: string = 'Ana' - tipo explicito", "function sumar(a: number, b: number): number { return a + b } - tipos en funciones", "interface Usuario { id: number; nombre: string } - definir estructura"],
        "difficulty": "TypeScript es facil si ya sabes JavaScript. El sistema de tipos es lo mas complejo pero tambien lo mas util.",
    },
    "vue": {
        "what": "Vue.js es un framework JavaScript progresivo para construir interfaces de usuario. Creado por Evan You en 2014.",
        "how": "Vue usa un sistema de reactividad basado en proxies. Los componentes tienen template (HTML), script (JS) y style (CSS) en un solo archivo .vue.",
        "why": "Vue es facil de aprender, muy flexible, y su curva de aprendizaje es suave comparado con React o Angular.",
        "purpose": "Vue sirve para crear interfaces web interactivas, SPAs, y componentes reutilizables.",
        "examples": ["<template><h1>{{ mensaje }}</h1></template> - template con datos", "const app = Vue.createApp({ data() { return { mensaje: 'Hola' } } })", "v-if, v-for, v-model - directivas de Vue"],
        "difficulty": "Vue es de los frameworks mas faciles de aprender. Su documentacion es excelente.",
    },
    "angular": {
        "what": "Angular es un framework web completo de Google para crear aplicaciones de una sola pagina (SPA) con TypeScript.",
        "how": "Angular usa TypeScript, inyeccion de dependencias, RxJS para observables, y un sistema de modulos. Tiene CLI propio para generar codigo.",
        "why": "Angular es ideal para proyectos grandes y empresariales porque opiniona la arquitectura y trae todo incluido.",
        "purpose": "Angular sirve para crear aplicaciones web empresariales, dashboards complejos, y SPAs robustas.",
        "examples": ["@Component({ selector: 'app-hola', template: '<h1>Hola</h1>' }) - componente", "@Injectable() - servicio inyectable", "ng generate component nombre - generar componente con CLI"],
        "difficulty": "Angular es el mas dificil de los 3 grandes (React, Vue, Angular). Requiere saber TypeScript y tener experiencia.",
    },
    "nextjs": {
        "what": "Next.js es un framework de React creado por Vercel que agrega renderizado del lado del servidor (SSR), generacion estatica (SSG), y mas.",
        "how": "Next.js puede renderizar paginas en el servidor (SSR) o generarlas estaticamente (SSG). Soporta rutas dinamicas, API routes, y optimizaciones automaticas.",
        "why": "Next.js resuelve las limitaciones de React puro: SEO, velocidad de carga inicial, y routing basado en archivos.",
        "purpose": "Next.js sirve para crear sitios web rapidos, optimizados para SEO, y aplicaciones web completas con backend incluido.",
        "examples": ["pages/index.js - pagina principal", "pages/about.js - ruta /about", "getServerSideProps() - SSR"],
        "difficulty": "Next.js es accesible si ya sabes React. SSR y SSG pueden confundir al principio.",
    },
    "mongo": {
        "what": "MongoDB es una base de datos NoSQL basada en documentos. Guarda datos en formato BSON (JSON binario) en lugar de tablas.",
        "how": "MongoDB organiza datos en colecciones (como tablas) y documentos (como filas). Usa un lenguaje de consultas flexible y escalabilidad horizontal.",
        "why": "MongoDB es ideal para datos que cambian frecuentemente, estructuras flexibles, y aplicaciones que necesitan escalar horizontalmente.",
        "purpose": "MongoDB sirve para almacenar datos de aplicaciones web, analiticos, contenido, y datos en tiempo real.",
        "examples": ["db.usuarios.insertOne({nombre: 'Ana', edad: 25}) - insertar documento", "db.usuarios.find({edad: {$gt: 18}}) - buscar mayores de 18", "db.usuarios.updateOne({nombre: 'Ana'}, {$set: {edad: 26}}) - actualizar"],
        "difficulty": "MongoDB es facil de empezar si vienes de JSON. Las consultas complejas y la modelizacion de datos requieren practica.",
    },
    "redis": {
        "what": "Redis es una base de datos en memoria ultra-rapida. Se usa como cache, cola de mensajes, y almacenamiento de sesiones.",
        "how": "Redis guarda todo en la memoria RAM, lo que lo hace extremadamente rapido. Soporta estructuras como strings, hashes, listas, sets y sorted sets.",
        "why": "Redis es ideal para cacheo, sesiones, colas de tareas, y cualquier cosa que necesite velocidad extrema.",
        "purpose": "Redis sirve para cache de consultas, sesiones de usuario, colas de mensajes, contadores, y rate limiting.",
        "examples": ["SET nombre 'Ana' - guardar string", "GET nombre - obtener valor", "EXPIRE nombre 3600 - expirar en 1 hora"],
        "difficulty": "Redis basico es muy facil. Las estructuras de datos y los patrones de uso avanzados requieren mas estudio.",
    },
    "aws": {
        "what": "Amazon Web Services (AWS) es la plataforma de cloud computing mas grande del mundo. Ofrece mas de 200 servicios de servidores, almacenamiento, bases de datos, IA y mas.",
        "how": "AWS funciona bajo modelos IaaS, PaaS y SaaS. Puedes alquilar servidores virtuales (EC2), almacenar archivos (S3), usar bases de datos (RDS), y mucho mas.",
        "why": "AWS permite escalar aplicaciones sin comprar hardware, pagar solo por lo que usas, y desplegar globalmente.",
        "purpose": "AWS sirve para hospedar aplicaciones web, almacenar datos, crear APIs, entrenar modelos de IA, y construir infraestructura completa en la nube.",
        "examples": ["EC2 - servidores virtuales", "S3 - almacenamiento de archivos", "Lambda - funcion serverless"],
        "difficulty": "AWS basico es entendible. La cantidad de servicios y configuraciones puede ser abrumadora.",
    },
    "terraform": {
        "what": "Terraform es una herramienta de HashiCorp para infraestructura como codigo (IaC). Permite crear y gestionar infraestructura en la nube con archivos de configuracion.",
        "how": "Terraform usa archivos .hcl para describir la infraestructura deseada. Compara el estado actual con el deseado y hace cambios automaticamente.",
        "why": "Terraform permite versionar la infraestructura, reproducir ambientes, y automatizar despliegues complejos.",
        "purpose": "Terraform sirve para crear y gestionar servidores, redes, bases de datos, y cualquier recurso de nube de forma declarativa.",
        "examples": ["resource 'aws_instance' 'web' { ami = '...' } - crear instancia EC2", "terraform plan - ver cambios que se harian", "terraform apply - aplicar cambios"],
        "difficulty": "Terraform requiere saber cloud basico y un proveedor (AWS, Azure, GCP). La sintaxis HCL es sencilla.",
    },
    "flutter": {
        "what": "Flutter es un SDK de Google para crear aplicaciones moviles nativas para Android e iOS con un solo codigo fuente. Usa el lenguaje Dart.",
        "how": "Flutter compila a codigo nativo ARM. Usa widgets personalizables que se renderizan directamente en el canvas, sin depender de widgets nativos del SO.",
        "why": "Flutter permite crear apps nativas rapidas y bonitas con un solo equipo de desarrollo, reduciendo costos y tiempo.",
        "purpose": "Flutter sirve para crear apps moviles, apps de escritorio (Flutter Desktop), y hasta apps web.",
        "examples": ["MaterialApp(home: Scaffold(body: Text('Hola'))) - app basica", "ElevatedButton(onPressed: () {}, child: Text('Click')) - boton", "flutter run - ejecutar en emulador"],
        "difficulty": "Flutter es accesible si sabes un lenguaje orientado a objetos. Dart es facil de aprender.",
    },
    "kotlin": {
        "what": "Kotlin es un lenguaje de programacion moderno que corre en la JVM. Es el lenguaje oficial para desarrollo Android.",
        "how": "Kotlin compila a bytecode de JVM o a JavaScript. Es 100% interoperable con Java y tiene features modernas como null safety, coroutines y extension functions.",
        "why": "Kotlin es mas conciso y seguro que Java, y es el lenguaje recomendado por Google para Android.",
        "purpose": "Kotlin sirve para desarrollo Android, backend con Ktor/Spring, y multiplataforma con Kotlin Multiplatform.",
        "examples": ["val nombre: String = 'Ana' - variable inmutable", "fun saludar(nombre: String) = 'Hola $nombre' - funcion", "data class Usuario(val id: Int, val nombre: String) - data class"],
        "difficulty": "Kotlin es facil si vienes de Java o un lenguaje moderno. Null safety puede confundir al principio.",
    },
    "swift": {
        "what": "Swift es un lenguaje de programacion de Apple para crear apps de iOS, macOS, watchOS y tvOS.",
        "how": "Swift compila a codigo nativo optimizado. Tiene un sistema de tipos robusto, optionals para null safety, y es mucho mas rapido que Objective-C.",
        "why": "Swift es el lenguaje oficial de Apple para desarrollo de apps. Es mas seguro, rapido y moderno que Objective-C.",
        "purpose": "Swift sirve para crear apps de iPhone, iPad, Mac, Apple Watch, y Apple TV.",
        "examples": ["let nombre = 'Ana' - constante", "func saludar(nombre: String) -> String { return 'Hola \\(nombre)' }", "struct Usuario { let id: Int; let nombre: String }"],
        "difficulty": "Swift es accesible. Si sabes un lenguaje moderno, Swift es facil de aprender.",
    },
    "rust": {
        "what": "Rust es un lenguaje de programacion de sistemas enfocado en seguridad, velocidad y concurrencia. Creado por Mozilla.",
        "how": "Rust usa un sistema de ownership y borrowing que garantiza seguridad de memoria sin garbage collector. Compila a codigo nativo ultra-rapido.",
        "why": "Rust elimina clases enteras de bugs (data races, null pointers) en tiempo de compilacion sin sacrificar rendimiento.",
        "purpose": "Rust sirve para sistemas operativos, navegadores (Firefox), herramientas CLI, WebAssembly, y software de alto rendimiento.",
        "examples": ["let mut x = 5; x += 1; - variable mutable", "fn sumar(a: i32, b: i32) -> i32 { a + b } - funcion", "match opcion { Some(v) => v, None => 0 } - pattern matching"],
        "difficulty": "Rust es dificil. El sistema de ownership es unico y confunde al principio, pero es muy poderoso.",
    },
    "go": {
        "what": "Go (Golang) es un lenguaje de programacion de Google disenado para simplicidad, eficiencia y concurrencia.",
        "how": "Go compila rapidamente a codigo nativo. Tiene goroutines para concurrencia facil, un garbage collector, y un ecosistema de herramientas excellent.",
        "why": "Go es simple, rapido, y ideal para servicios de red, microservicios, y herramientas de DevOps.",
        "purpose": "Go sirve para APIs, microservicios, herramientas CLI (Docker, Kubernetes estan hechos en Go), y sistemas distribuidos.",
        "examples": ["func main() { fmt.Println('Hola') } - programa basico", "go func() { fmt.Println('async') }() - goroutine", "http.HandleFunc('/', handler) - servidor web"],
        "difficulty": "Go es intencionalmente simple. Es uno de los lenguajes mas faciles de aprender.",
    },
    "c++": {
        "what": "C++ es un lenguaje de programacion de proposito general, compilado, orientado a objetos y de alto rendimiento. Extiende C con clases, templates y STL.",
        "how": "C++ compila directamente a codigo de maquina. Ofrece control manual de memoria (new/delete, smart pointers), plantillas para genericos, y la STL (contenedores, algoritmos, iteradores).",
        "why": "C++ combina abstracciones de alto nivel con control de bajo nivel. Es el estandar en juegos, sistemas embebidos, trading de alta frecuencia, y software critico de rendimiento.",
        "purpose": "C++ sirve para motores de juegos (Unreal Engine), sistemas operativos, navegadores, bases de datos, simulaciones, y cualquier software donde el rendimiento es critico.",
        "examples": ["std::vector<int> v = {1,2,3}; - vector dinamico", "std::unique_ptr<int> p = std::make_unique<int>(42); - smart pointer", "template <typename T> T max(T a, T b) { return a > b ? a : b; } - template"],
        "difficulty": "C++ es dificil. Requiere entender punteros, memoria, templates, y la STL. Curva de aprendizaje empinada pero muy gratificante.",
    },
    "sass": {
        "what": "SASS (Syntactically Awesome Stylesheets) es un preprocesador de CSS que agrega features como variables, nesting, mixins y funciones.",
        "how": "SASS compila a CSS vanilla. Agrega variables ($color), anidamiento (.nav { .item {} }), mixins (@mixin), y archivos parciales.",
        "why": "SASS hace el CSS mas mantenible, reutilizable y organizado, especialmente en proyectos grandes.",
        "purpose": "SASS sirve para escribir CSS mas organizado y potente en proyectos web grandes.",
        "examples": ["$primary: #57a6ff; - variable", ".nav { .item { color: $primary; } } - nesting", "@mixin flex-center { display: flex; align-items: center; justify-content: center; } - mixin"],
        "difficulty": "SASS es facil si ya sabes CSS. Las variables y mixins son intuitivos.",
    },
    "webpack": {
        "what": "Webpack es un bundler de JavaScript que empaleta todos los assets de una aplicacion (JS, CSS, imagenes) en archivos optimizados.",
        "how": "Webpack construye un grafo de dependencias a partir de un archivo de entrada y lo compila en bundles optimizados con loaders y plugins.",
        "why": "Webpack permite usar modulos ES6, TypeScript, SASS, y otros lenguajes que el navegador no entiende directamente.",
        "purpose": "Webpack sirve para compilar, optimizar y empaquetar codigo frontend para produccion.",
        "examples": ["entry: './src/index.js' - archivo de entrada", "output: { filename: 'bundle.js' } - archivo de salida", "loaders: [babel-loader, css-loader] - transformar archivos"],
        "difficulty": "Webpack basico es entendible. La configuracion avanzada (loaders, plugins, code splitting) es compleja.",
    },
    "babel": {
        "what": "Babel es un compilador de JavaScript que transforma codigo moderno (ES6+) en versiones compatibles con navegadores antiguos.",
        "how": "Babel usa un sistema de plugins y presets para transformar el codigo. Puede convertir JSX, optional chaining, y otras features nuevas.",
        "why": "Babel permite usar las ultimas features de JavaScript sin preocuparte por la compatibilidad con navegadores viejos.",
        "purpose": "Babel sirve para transpilar JavaScript moderno, JSX de React, y TypeScript a JS compatible.",
        "examples": ["npx babel src --out-dir lib - compilar carpeta", "babel.config.json: { presets: ['@babel/preset-env'] } - configuracion", "JSX -> React.createElement() - transformacion"],
        "difficulty": "Babel basico es facil. Configurar plugins y presets para proyectos complejos requiere mas experiencia.",
    },
    "npm": {
        "what": "npm (Node Package Manager) es el gestor de paquetes oficial de Node.js. Tiene el repositorio de paquetes open source mas grande del mundo.",
        "how": "npm descarga paquetes de registry.npmjs.com, los instala en node_modules/, y gestiona dependencias en package.json.",
        "why": "npm permite reutilizar codigo de otros desarrolladores, gestionar versiones, y automatizar tareas de desarrollo.",
        "purpose": "npm sirve para instalar, actualizar y gestionar paquetes de JavaScript y herramientas de desarrollo.",
        "examples": ["npm init - crear package.json", "npm install express - instalar paquete", "npm run dev - ejecutar script"],
        "difficulty": "npm basico es muy facil. El manejo de dependencias, versiones y conflictos puede ser complejo.",
    },
    "php": {
        "what": "PHP es un lenguaje de script del lado del servidor disenado para el desarrollo web. Es el lenguaje de WordPress, Facebook (HHVM) y millones de sitios.",
        "how": "PHP se ejecuta en el servidor, genera HTML, y lo envia al navegador. Soporta multiples bases de datos y tiene un ecosistema enorme.",
        "why": "PHP es facil de aprender, tiene hosting barato, y powers el 77% de la web con WordPress alone.",
        "purpose": "PHP sirve para crear sitios web dinamicos, CMS (WordPress), APIs, y aplicaciones web completas (Laravel).",
        "examples": ["<?php echo 'Hola Mundo'; ?> - imprimir texto", "$nombre = 'Ana'; - variable", "echo json_encode($datos); - output JSON"],
        "difficulty": "PHP es facil de empezar. La calidad del codigo puede variar mucho dependiendo del framework.",
    },
    "ruby": {
        "what": "Ruby es un lenguaje de programacion orientado a objetos creado por Yukihiro Matsumoto. Es conocido por su elegancia y por Ruby on Rails.",
        "how": "Ruby es interpretado, tiene tipado dinamico, y es todo un objeto. Ruby on Rails es un framework web full-stack que sigue convenciones sobre configuracion.",
        "why": "Ruby prioriza la felicidad del programador. Ruby on Rails acelera enormemente el desarrollo web.",
        "purpose": "Ruby sirve para desarrollo web (Rails), scripting, automatizacion, y prototipos rapidos.",
        "examples": ["nombre = 'Ana' - variable", "def saludar(nombre); puts \"Hola #{nombre}\"; end - metodo", "User.where(age: 18).order(:name) - consulta Rails"],
        "difficulty": "Ruby es facil y agradable de usar. Rails tiene una curva de aprendizaje suave pero mucho que memorizar.",
    },
    "django": {
        "what": "Django es un framework web completo para Python que sigue el patron MVT (Model-View-Template).",
        "how": "Django trae ORM, admin panel, autenticacion, routing, templates, y seguridad integrada. Sigue el principio de 'baterias incluidas'.",
        "why": "Django es ideal para proyectos web complejos porque trae todo lo necesario listo para usar.",
        "purpose": "Django sirve para crear APIs REST, dashboards, CMS, e-commerce, y cualquier tipo de aplicacion web.",
        "examples": ["python manage.py startapp miapp - crear app", "models.py: class Usuario(models.Model): nombre = models.CharField()", "python manage.py runserver - iniciar servidor"],
        "difficulty": "Django es accesible si sabes Python. La cantidad de features puede ser abrumadora al principio.",
    },
    "laravel": {
        "what": "Laravel es un framework web para PHP creado por Taylor Otwell. Es el framework PHP mas popular y elegante.",
        "how": "Laravel usa el patron MVC, tiene Blade para templates, Eloquent ORM, migraciones, y artisan CLI. Sigue la filosofia de convention over configuration.",
        "why": "Laravel hace PHP moderno y productivo. Tiene una comunidad enorme y documentacion excelente.",
        "purpose": "Laravel sirve para crear APIs REST, aplicaciones web completas, e-commerce, y dashboards.",
        "examples": ["Route::get('/users', [UserController::class, 'index']) - ruta", "User::where('age', '>', 18)->get() - consulta Eloquent", "php artisan make:model Usuario - generar modelo"],
        "difficulty": "Laravel es accesible si sabes PHP. Blade y Eloquent son intuitivos.",
    },
    "api": {
        "what": "Una API (Application Programming Interface) es un contrato que define como dos software se comunican entre si.",
        "how": "Una API define endpoints (URLs), metodos HTTP (GET, POST, PUT, DELETE), y formatos de datos (JSON, XML). El cliente envia peticiones y recibe respuestas.",
        "why": "Las APIs permiten que diferentes sistemas se conecten: una app movil habla con un servidor, un sitio web consulta una base de datos externa, etc.",
        "purpose": "Las APIs sirven para conectar servicios, exponer funcionalidades, e integrar sistemas diferentes.",
        "examples": ["GET /api/usuarios - obtener lista de usuarios", "POST /api/usuarios - crear un usuario nuevo", "DELETE /api/usuarios/1 - borrar usuario con id 1"],
        "difficulty": "APIs basicas son faciles. Las APIs complejas con autenticacion, paginacion y versionado requieren mas experiencia.",
    },
}

